trigger:
  paths:
    exclude:
      - src/Rhisis.ClusterServer
      - src/Rhisis.WorldServer
  branches:
    exclude:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- script: |
    dotnet build src/Rhisis.LoginServer/Rhisis.LoginServer.csproj --configuration Release
  displayName: 'Build'
