# ===========================================
# Docker Compose file for Visual Studio debug 
# ===========================================

version: '3.5'
services:
  rhisis.loginserver:
    image: ${DOCKER_REGISTRY-}rhisislogin
    build:
      context: .
      dockerfile: src/Rhisis.LoginServer/Dockerfile
    depends_on:
      - rhisis.database
    ports:
      - "23000:23000"
    expose: 
      - 23000
    environment:
      RHISIS_CONFIGURATION: /opt/rhisis
    volumes:
     - "./bin/config/login.json:/opt/rhisis/config/login.json:ro"
     - "./bin/config/core.json:/opt/rhisis/config/core.json:ro"
     - "./bin/config/database.json:/opt/rhisis/config/database.json:ro"
     - "./bin/logs/login:/opt/rhisis/logs/login"

  rhisis.clusterserver:
    image: ${DOCKER_REGISTRY-}rhisiscluster
    build:
      context: .
      dockerfile: src/Rhisis.ClusterServer/Dockerfile
    depends_on:
      - rhisis.loginserver
      - rhisis.database
      - rhisis.redis
    ports:
      - "28000:28000"
    expose:
      - 28000
    environment:
      RHISIS_CONFIGURATION: /opt/rhisis
    volumes:
     - "./bin/config/cluster.json:/opt/rhisis/config/cluster.json:ro"
     - "./bin/config/database.json:/opt/rhisis/config/database.json:ro"
     - "./bin/logs/cluster:/opt/rhisis/logs/cluster"
     - "./bin/data:/opt/rhisis/data:ro"

  rhisis.worldserver:
    image: ${DOCKER_REGISTRY-}rhisisworldserver
    build:
      context: .
      dockerfile: src/Rhisis.WorldServer/Dockerfile
    depends_on:
      - rhisis.loginserver
      - rhisis.clusterserver
      - rhisis.database
      - rhisis.redis
    ports:
      - "5400:5400"
    expose:
      - 5400
    environment:
      RHISIS_CONFIGURATION: /opt/rhisis
    volumes:
     - "./bin/config/world.json:/opt/rhisis/config/world.json:ro"
     - "./bin/config/database.json:/opt/rhisis/config/database.json:ro"
     - "./bin/logs/world:/opt/rhisis/logs/world"
     - "./bin/data:/opt/rhisis/data:ro"

  rhisis.database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - ./bin/_docker/mysql:/var/lib/mysql

  rhisis.redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./bin/_docker/redis/:/data
