server:
  ip: '127.0.0.1'
  port: 28000
  name: 'Rhisis'
  login-protect: false
  default-character:
    man:
      level: 1
      gold: 0
      strength: 15
      stamina: 15
      dexterity: 15
      intelligence: 15
      map: 1
      pos-x: 6968
      pos-y: 100
      pos-z: 3328
      equiped:
        hat: -1
        body: II_ARM_M_VAG_SUIT01
        hand: II_ARM_M_VAG_GAUNTLET01
        boots: II_ARM_M_VAG_BOOTS01
        right-weapon: II_WEA_SWO_WOODEN
        left-weapon: -1
      inventory: []
    woman:
      level: 1
      gold: 0
      strength: 15
      stamina: 15
      dexterity: 15
      intelligence: 15
      map: 1
      pos-x: 6968
      pos-y: 100
      pos-z: 3328
      equiped:
        hat: -1
        body: II_ARM_F_VAG_SUIT01
        hand: II_ARM_F_VAG_GAUNTLET01
        boots: II_ARM_F_VAG_BOOTS01
        right-weapon: II_WEA_SWO_WOODEN
        left-weapon: -1
      inventory: []
cluster-cache-server:
  ip: '127.0.0.1'
  port: 16000
  master-password: 'StrongPassword'
core-cache:
  ip: '127.0.0.1'
  port: 15000
  master-password: 'StrongPassword'
account-database:
  provider: 'sqlite'
  connection-string: 'Data Source=./data/db/accounts.db;'
game-database:
  provider: 'sqlite'
  connection-string: 'Data Source=./data/db/game.db;'

