// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Rhisis.Database.Context;
using System;

namespace Rhisis.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180825131109_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Rhisis.Database.Entities.DbCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Angle");

                    b.Property<int>("BankCode");

                    b.Property<int>("ClassId");

                    b.Property<int>("Dexterity");

                    b.Property<long>("Experience");

                    b.Property<int>("FaceId");

                    b.Property<int>("Fp");

                    b.Property<byte>("Gender");

                    b.Property<int>("Gold");

                    b.Property<int>("HairColor");

                    b.Property<int>("HairId");

                    b.Property<int>("Hp");

                    b.Property<int>("Intelligence");

                    b.Property<int>("Level");

                    b.Property<int>("MapId");

                    b.Property<int>("MapLayerId");

                    b.Property<int>("Mp");

                    b.Property<string>("Name");

                    b.Property<float>("PosX");

                    b.Property<float>("PosY");

                    b.Property<float>("PosZ");

                    b.Property<int>("SkillPoints");

                    b.Property<int>("SkinSetId");

                    b.Property<int>("Slot");

                    b.Property<int>("Stamina");

                    b.Property<int>("StatPoints");

                    b.Property<int>("Strength");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterId");

                    b.Property<int>("CreatorId");

                    b.Property<byte>("Element");

                    b.Property<byte>("ElementRefine");

                    b.Property<int>("ItemCount");

                    b.Property<int>("ItemId");

                    b.Property<int>("ItemSlot");

                    b.Property<byte>("Refine");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Authority");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbMail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SenderId");

                    b.Property<int>("ReceiverId");

                    b.Property<uint>("Gold");

                    b.Property<int?>("ItemId");

                    b.Property<short>("ItemQuantity");

                    b.Property<string>("Title");

                    b.Property<string>("Text");

                    b.Property<bool>("HasBeenRead");

                    b.Property<bool>("HasReceivedItem");

                    b.Property<bool>("HasReceivedGold");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("CreateTime");

                    b.HasKey("Id");

                    b.ToTable("mails");
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbCharacter", b =>
                {
                    b.HasOne("Rhisis.Database.Entities.DbUser", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbItem", b =>
                {
                    b.HasOne("Rhisis.Database.Entities.DbCharacter", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
            modelBuilder.Entity("Rhisis.Database.Entities.DbMail", b =>
                {
                    b.HasOne("Rhisis.Database.Entities.DbCharacter", "Receiver")
                        .WithMany("Mails")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
