// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rhisis.Database.Context;

namespace Rhisis.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190223194344_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rhisis.Database.Entities.DbCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Angle");

                    b.Property<int>("BankCode");

                    b.Property<int>("ClassId");

                    b.Property<int>("Dexterity");

                    b.Property<long>("Experience");

                    b.Property<int>("FaceId");

                    b.Property<int>("Fp");

                    b.Property<byte>("Gender");

                    b.Property<int>("Gold");

                    b.Property<int>("HairColor");

                    b.Property<int>("HairId");

                    b.Property<int>("Hp");

                    b.Property<int>("Intelligence");

                    b.Property<int>("Level");

                    b.Property<int>("MapId");

                    b.Property<int>("MapLayerId");

                    b.Property<int>("Mp");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<float>("PosX");

                    b.Property<float>("PosY");

                    b.Property<float>("PosZ");

                    b.Property<int>("SkillPoints");

                    b.Property<int>("SkinSetId");

                    b.Property<int>("Slot");

                    b.Property<int>("Stamina");

                    b.Property<int>("StatPoints");

                    b.Property<int>("Strength");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CharacterId");

                    b.Property<int>("CreatorId");

                    b.Property<byte>("Element");

                    b.Property<byte>("ElementRefine");

                    b.Property<int>("ItemCount");

                    b.Property<int>("ItemId");

                    b.Property<int>("ItemSlot");

                    b.Property<byte>("Refine");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbMail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<long>("Gold")
                        .HasColumnType("BIGINT");

                    b.Property<bool>("HasBeenRead");

                    b.Property<bool>("HasReceivedGold");

                    b.Property<bool>("HasReceivedItem");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("ItemId");

                    b.Property<short>("ItemQuantity");

                    b.Property<int>("ReceiverId");

                    b.Property<int>("SenderId");

                    b.Property<string>("Text");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("mails");
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbShortcut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CharacterId");

                    b.Property<uint>("ObjectData");

                    b.Property<uint>("ObjectId");

                    b.Property<uint>("ObjectIndex");

                    b.Property<uint>("ObjectType");

                    b.Property<int>("SlotIndex");

                    b.Property<int?>("SlotLevelIndex");

                    b.Property<int>("TargetTaskbar");

                    b.Property<string>("Text");

                    b.Property<uint>("Type");

                    b.Property<uint>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("shortcuts");
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Authority");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<DateTime>("LastConnectionTime")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbCharacter", b =>
                {
                    b.HasOne("Rhisis.Database.Entities.DbUser", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbItem", b =>
                {
                    b.HasOne("Rhisis.Database.Entities.DbCharacter", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbMail", b =>
                {
                    b.HasOne("Rhisis.Database.Entities.DbItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Rhisis.Database.Entities.DbCharacter", "Receiver")
                        .WithMany("ReceivedMails")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rhisis.Database.Entities.DbCharacter", "Sender")
                        .WithMany("SentMails")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rhisis.Database.Entities.DbShortcut", b =>
                {
                    b.HasOne("Rhisis.Database.Entities.DbCharacter", "Character")
                        .WithMany("TaskbarShortcuts")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
